name: Run Azure Login with OpenID Connect
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
    
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          clientid: ${{ secrets.AZURE_CLIENT_ID }}
          tenantid: ${{ secrets.AZURE_TENANT_ID }}
          subscriptionid: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 